### PR TITLE
Fixes for line endings, whitespaces and code style

### PR DESCRIPTION
**Pull request by fschrempf**
The first three commits are cleanup work, fixing the line endings, trailing whitespaces, indentation, and other code-style issues. The last commit fixes the missing slash in the closing div tags, introduced by https://github.com/turnermm/nodisp/commit/3a687bb6cfe4251fb2d2f74ea49793af64559d1b.

### CODE REVIEW

**Comment by turnermm** [comment]
Please make these individual pulls.  I'd like to first fix the div problem that you have noted.  Thanks.

**Comment by fschrempf** [comment]
@turnermm You've already applied the div fix, which is ok, but instead of authoring the change by yourself a much better way would have been to just cherry-pick my commit and keep my authorship, or waiting for me to create a separate PR, if you really want it the other way round.

Anyway, I rebased the cleanups on the new master and updated this PR.

**Comment by turnermm** [comment]
I simply wanted to see what the div change was, but when I extracted it from the pull it  was such a simple change that I left it.  I would have used your commit but didn't know how to do it without taking along the rest of your changes and didn't want to have to review those at this time, since they aren't critical.   I'll do that as soon as I can and get back to you.

**Comment by fschrempf** [comment]
>  I would have used your commit but didn't know how to do it without taking along the rest of your changes

As I said, fetching my branch, cherry-picking the fix and resolving the conflict should have done the job, but never mind.

**Comment by turnermm** [comment]
The point is that you should have made separate pulls for each set of changes. Instead, I was confronted with a jig-saw puzzle of changes. I am responsible for close to 40 different plugins, some with thousands of lines.

**Comment by fschrempf** [comment]
> The point is that you should have made separate pulls for each set of changes.

Have you looked at the changes? How should I split them up? They touch all of the code and therefore depend on each other. If I would split the three commits into three PRs, the second and third one still couldn't be applied without the ones before.

> I was confronted with a jig-saw puzzle of changes

Sorry, but I can't really see the problem or how I could have done this any better. But if you have any specific advice, I'll be glad to hear it. All these changes are done automatically and are purely cosmetic. If you hide the whitespace changes, there's not much left to review: https://github.com/turnermm/nodisp/pull/2/files?diff=split&w=1.

**Comment by turnermm** [comment]
Since you've gone to the trouble of doing this, I felt it was only fair to look over your changes.  
1. The styling of function definitions.  Your changes involve moving the curly brace from the end of the line to the line following:  
```
     function abc() { 
     function abc() 
     {
```
Bit in fact the first form, which I use, is DokuiWiki coding style.

2. The style for preg_replace_callback which I use is consistent with the style found on the official php web site at php.net.  

These were things that immediately caught my attention.  The tools which you are using may be "prettifying", and there's no doubt that some of my spacing my be in need of tightening up,  but I didn't notice anything that seemed to be in great need of fixing.

**Comment by fschrempf** [comment]
Ok, got it, thanks for checking. I appreciate people properly reviewing changes!

Indeed some of the changes in the last commit (https://github.com/turnermm/nodisp/pull/2/commits/94d0e77cdfa3a7598c1ba507c7aa4cd9b7cf517b) are "prettifying" as done by the VSCode and PHP Intelephense, though to me it really looks much nicer than before. If you rather want to keep the "old" style, I can update this commit to only fix the indentation.

**Comment by turnermm** [comment]
I'vw updated the version for the `div` fix and given you credit in the commit message for the  fix.  Thanks.

**Comment by fschrempf** [comment]
> If you rather want to keep the "old" style, I can update this commit to only fix the indentation.
 
So I removed all the code style changes, except for whitespace fixes. This is now the bare minimum of what I think should be fixed (line endings, indentation and whitespaces). Without these it's really difficult and annoying for anyone to actually work with the code in any way.

**Comment by turnermm** [comment]
A major revision is in progress, so that these changes no longer apply. Thanks for your efforts.

**Pull request closed without merging**
